superdesk/superdesk-belga

server/data/vocabularies.json
=> [VOCABULARIES] Added vocabularies coming from legacy Belga system

client/superdesk.config.js, server/data/content_types.json, server/data/vocabularies.json, server/settings.py
- Rearrange fields in content profile, mark distribution as a single value field
- Belga related settings
- Client config updates
=> SDBELGA-37

client/superdesk.config.js, server/belga/image.py, server/tests/belga_image_test.py
- avoid fetching images when using it
- fix images count
SDBELGA-72
=> belga image improvements

server/settings.py
Added validation config for multimedia
=> Added validation config for multimedia

server/settings.py
added schema and editor config for pictures, video, audio
updated config for VALIDATOR_MEDIA_METADATA
=> added schema and editor config for multimedia

client/belga/image/BelgaSearchPanelController.ts
it's hardcoded in their client, so copied it here.
SDBELGA-83
=> add missing belga image subjects

server/settings.py
set publish queue expiry to 10 days
changed fields for media validation
=> update publish queue expiry, multimedia validation

server/belga/image.py
using graphic type so we can distinguish between pictures and coverages
SDBELGA-85
=> add initial belga coverage support

server/settings.py, server/setup.cfg
=> set template for planning export as article

server/data/planning_export_templates.json, server/templates/planning_multiple_agendas_template.html
SDBELGA-110
The resulting export will be an article listing agendas with each exported item as a child of the agenda
=> Template to export items with multiple agendas

server/belga/image.py, server/tests/belga_image_test.py
=> implement auth for belga image/coverage

server/data/planning_export_templates.json, server/templates/planning_multiple_agendas_internal_template.html, server/templates/planning_multiple_agendas_template.html
SDBELGA-129
Includes a new template: "Internal"
Needs https://github.com/superdesk/superdesk-planning/pull/1243
=> Show other agendas for each item in "multiple agendas export"

server/belga/io/feeding_services/__init__.py, server/belga/io/feeding_services/email_belga.py, server/tests/io/feeding_services/email_belga_test.py, server/tests/io/fixtures/email_attachment_belga.txt
Register new feeding service Email Belga.
Add function email attachment:
+ get attachment from email.
+ save file to storage and attachments collection.
+ add value for 'ednote' property and save attachment id to ingest item
=> [ SDBELGA-130] Add email attachment for Belga

server/templates/planning_multiple_agendas_internal_template.html
SDBELGA-129
Needs https://github.com/superdesk/superdesk-planning/pull/1281
=> Show coverage even when there is no user assigned

client/package.json, server/requirements.txt
- Client core to 1.31.0
- Server core to 1.31.2
- Planning to 1.6.2
=> Updates Superdesk dependencies

server/settings.py
SDBELGA-101
SDBELGA-102
SDBELGA-103
=> enable event templates

server/Procfile
=> Add production api to Procfile.

client/superdesk.config.js
=> display translations in list view

server/Procfile, server/belga/io/feed_parsers/__init__.py, server/belga/io/feed_parsers/belga_tip_newsml_1_2.py, server/tests/io/feed_parsers/belga_tip_newsml_1_2_test.py, server/tests/io/fixtures/belga_tip_newsml_1_2.xml
- add new feed parser Belga tip format
- add unit test
=> [SDBELGA-172] Tip ingest

client/superdesk.config.js
Requires https://github.com/superdesk/superdesk-client-core/pull/3164
=> Add custom buttons in the authoring topbar. (SDBELGA-197)

server/data/vocabularies.json
=> SDBELGA-198 Multilingual CV for countries

server/belga/io/feed_parsers/base_belga_newsml_1_2.py, server/belga/io/feed_parsers/belga_afp_newsml_1_2.py, server/belga/io/feed_parsers/belga_anp_newsml_1_2.py, server/belga/io/feed_parsers/belga_anpa.py, server/belga/io/feed_parsers/belga_efe_newsml_1_2.py, server/belga/io/feed_parsers/belga_iptc7901.py, server/belga/io/feed_parsers/belga_tass_newsml_1_2.py, server/tests/io/feed_parsers/belga_afp_newsml_1_2_test.py, server/tests/io/feed_parsers/belga_anp_newsml_1_2_test.py, server/tests/io/feed_parsers/belga_anpa_test.py, server/tests/io/feed_parsers/belga_ats_newsml_1_2_test.py, server/tests/io/feed_parsers/belga_efe_newsml_1_2_test.py, server/tests/io/feed_parsers/belga_iptc7901_test.py, server/tests/io/feed_parsers/belga_tass_newsml_1_2_test.py, server/tests/io/fixtures/ats.txt, server/tests/io/fixtures/efe_belga.xml, server/tests/io/fixtures/tass_belga.xml
Update Ingest mapping from AFP,  ANP, TASS, EFE, ATS, KYODO,  DPA:
- Service is always equal NEWS
- Product have only one value (POLITICS, ECONOMY, SPORTS, GENERAL ...)
=> SDBELGA-202

server/belga/macros/__init__.py, server/belga/macros/add_prefix_to_headline.py, server/belga/macros/add_prefix_to_headline_test.py, server/settings.py
=> Create macro to add prefix BELG to headline. [SDBELGA-196]

server/data/vocabularies.json
Added init_version to Countries CV for it to be updated next time
=> Added init_version to Countries CV

server/data/vocabularies.json
changed qcodes - added prefix country_
=> Updated "Country" CV

server/data/vocabularies.json
A new services-products CV called "Packages" which is supposed to replace two separate CVs (news_services, news_products)
=> Add a new CV for Services and Products [SDBELGA-240]

client/superdesk.config.js
added  hideCreatePackage: true to features
=> Added config to hide package creation [SDBELGA-246]

client/superdesk.config.js
to move highlights and mark for desk to its previous position (more on left)
=> Updated list view

client/superdesk.config.js
=> Added config for search [SDBELGA-247]

server/belga/macros/set_default_metadata.py, server/belga/macros/set_default_metadata_test.py
=> [MACROS][SET_DEFAULT_METADATA] copy "services-products" +  added test

server/picture-profile.json
=> add missing mandatory fields

server/belga/update.py, server/settings.py, server/tests/update_test.py
=> change profile from ALERT to TEXT on update

server/belga/io/feed_parsers/__init__.py, server/belga/io/feed_parsers/belga_remote_newsml_1_2.py
=> [SDBELGA-272] Load Belga Remote parser

client/extensions/iptc/src/extension.ts, server/data/vocabularies.json, server/picture-profile.json
and handle default values from parent item in extension
SDBELGA-280
=> fix config for media profile

server/settings.py
=> set graphic type profile to include bcoverage

server/belga/publish/belga_newsml_1_2.py, server/tests/publish/belga_newsml_1_2_text_tests.py
=> SDBELGA-322 Update Text of Alert has wrong Role and misses validation date

client/extensions/belgaCoverage/src/belga-coverage-editor.tsx
requires https://github.com/superdesk/superdesk-client-core/pull/3369
SDBELGA-325
=> only allow belga coverages to drop into belga coverage field

server/belga/publish/belga_newsml_1_2.py
=> Use parent item validation date for Belga external items.

server/belga/macros/translate_sports_country_codes.py, server/tests/macros/translate_sports_country_codes_test.py
=> Translate Sports Country Codes macro should also work when format is (XXX/

server/belga/publish/belga_newsml_1_2.py, server/tests/publish/belga_newsml_1_2_items_chain_tests.py
=> Update of news has different enclosing item ID than the original

server/belga/publish/belga_newsml_1_2.py, server/tests/publish/belga_newsml_1_2_text_tests.py
=> Export URN as Superdesk media reference instead of URL in published NewsML

client/extensions/iptc/src/extension.ts, server/belga/io/feed_parsers/belga_afp_newsml_1_2.py, server/belga/io/feed_parsers/belga_anp_newsml_1_2.py, server/belga/io/feed_parsers/belga_anpa.py, server/belga/io/feed_parsers/belga_ats_newsml_1_2.py, server/belga/io/feed_parsers/belga_dpa_newsml_2_0.py, server/belga/io/feed_parsers/belga_efe_newsml_1_2.py, server/belga/io/feed_parsers/belga_iptc7901.py, server/belga/io/feed_parsers/belga_tass_newsml_1_2.py, server/belga/publish/belga_newsml_1_2.py, server/data/vocabularies.json, server/picture-profile.json, server/tests/io/feed_parsers/belga_afp_newsml_1_2_test.py, server/tests/io/feed_parsers/belga_anp_newsml_1_2_test.py, server/tests/io/feed_parsers/belga_anpa_test.py, server/tests/io/feed_parsers/belga_ats_newsml_1_2_test.py, server/tests/io/feed_parsers/belga_dpa_newsml_2_0_test.py, server/tests/io/feed_parsers/belga_efe_newsml_1_2_test.py, server/tests/io/feed_parsers/belga_iptc7901_test.py, server/tests/io/feed_parsers/belga_tass_newsml_1_2_test.py, server/tests/publish/belga_newsml_1_2_text_tests.py, server/tests/publish/belga_newsml_1_2_video_tests.py
=> Change "credit" to "source" and "media-credit" to "media-source"

server/settings.py
=> [GRAMMALECTE] Disabled typographic apostrophes and quotation marks

client/belga/index.tsx, client/package.json
=> use avatars from ui-framework

server/data/vocabularies.json
to use name "Country" and to be single selection
=> Modified "countries" CV

server/settings.py
Added config to generate short GUIDs
=> [SDBELGA-358] Generate short GUIDs

server/belga/publish/belga_newsml_1_2.py, server/tests/publish/belga_newsml_1_2_text_tests.py
SDBELGA-360
SDBELGA-361
SDBELGA-362
=> Newsml updates

client/package.json
required to fix the look of avatars
=> update ui framework to 2.1.17

server/settings.py
The idea is to avoid changing picture profile by reference https://github.com/superdesk/superdesk-belga/blob/master/server/settings.py#L152
=> Fix media profiles.

client/superdesk.config.js
Added "sources" and "languages"
=> Update search_cvs [SDBELGA-247]

server/data/vocabularies.json
aka "services-products", update  based on a Spreadsheet attached to a ticket
=> Updated "Packages" CV [SDBELGA-372]

server/data/vocabularies.json
new list built from scratch based on shared Google spreadsheet
=> Updated belga-keywords CV [SDBELGA-371]

server/data/vocabularies.json
=> Changed color for urgency 5

client/superdesk.config.js
=> Added langOverride [SDBELGA-317]

server/belga/generate_id_for_url.py, server/settings.py, server/tests/publish/belga_newsml_1_2_text_tests.py
=>  Generate id for URL field and reuse it between updates/translations

client/package.json, client/superdesk.config.js
SDBELGA-146
Config is the default except for `name`
=> Show name on assignments list

server/settings.py
SDBELGA-387
⚠️ requires ES reindex
=> Enable ES mapping for archive.extra

server/belga/search_providers.py, server/tests/search_providers/belga_360_archive_test.py
=> [SDBELGA-393] Add indentation for Belga Archive paragraph

server/belga/macros/set_default_metadata_with_translate.py
=> Set-Default-Metadata-With-Translate macro should switch off coming-up toggle

server/belga/publish/belga_newsml_1_2.py, server/tests/publish/belga_newsml_1_2_picture_tests.py, server/tests/publish/belga_newsml_1_2_text_tests.py, server/tests/publish/belga_newsml_1_2_video_tests.py
=> Change format of locally stored images/videos in the belga output.

.gitignore, server/belga/publish/belga_newsml_1_2.py, server/tests/publish/belga_newsml_1_2_text_tests.py
=> EDITOR and CORRESPONDENT types are exported to NewsML as AUTHOR

client/superdesk.config.js
=> fix search CVs

.fireq.json
related to https://github.com/superdesk/fireq/pull/72
=> Enable grammalecte in fireq

.travis.yml, server/belga/io/feed_parsers/belga_newsml_1_2.py, server/belga/macros/brief_internal_routing.py, server/belga/publish/belga_newsml_1_2.py, server/dev-requirements.txt, server/setup.cfg, server/tests/io/feeding_services/rss_belga_test.py
and update travis config, add mypy and fix mypy errors
=> Add move attachment config for BelgaNewsMLOneFeedParser

server/belga/macros/autopublish_in_30_sec.py
SDBELGA-425
related to https://github.com/superdesk/superdesk-core/pull/2033
Macro setup example:
=> Create a macro to be used to schedule items upon routing in ingest

server/belga/io/feed_parsers/belga_newsml_1_2.py, server/belga/publish/belga_newsml_1_2.py, server/tests/io/feed_parsers/belga_newsml_1_2_test.py, server/tests/io/feed_parsers/belga_tip_newsml_1_2_test.py, server/tests/io/fixtures/belga_newsml_1_2.xml, server/tests/macros/brief_internal_routing_macro_test.py, server/tests/publish/belga_newsml_1_2_text_tests.py
=> Recognition of BelgaRemote metadata

server/data/vocabularies.json
=> Add values to belga-keywords [SDBELGA-440]

server/belga/io/feed_parsers/base_belga_newsml_1_2.py, server/belga/io/feed_parsers/belga_afp_newsml_1_2.py, server/belga/io/feed_parsers/belga_dpa_newsml_2_0.py, server/tests/io/feed_parsers/belga_afp_newsml_1_2_test.py, server/tests/io/feed_parsers/belga_anp_newsml_1_2_test.py, server/tests/io/feed_parsers/belga_ats_newsml_1_2_test.py, server/tests/io/feed_parsers/belga_dpa_newsml_2_0_test.py, server/tests/io/feed_parsers/belga_efe_newsml_1_2_test.py
=> change urgency in dpa/afp ingest

server/belga/io/feed_parsers/belga_newsml_1_2.py, server/belga/io/feed_parsers/belga_tip_newsml_1_2.py, server/tests/io/feed_parsers/belga_newsml_1_2_test.py
SDBELGA-428
related to https://github.com/superdesk/superdesk-core/pull/2132
=> Ingest KeywordLine as belga-keywords.

server/settings.py
=> add audio profile

.github/workflows/tests.yml, server/belga/io/feed_parsers/belga_newsml_1_2.py, server/tests/io/feed_parsers/belga_newsml_1_2_test.py, server/tests/io/fixtures/belga_remote_newsml_1_2.xml
- handle author role properly
- set sources for belga
SDBELGA-450
=> fix belga newsml ingest

server/data/vocabularies.json
Add SHORTTRACK
remove duplicated entries for MUSIC
=> Update belga-keywords [SDBELGA-465]

server/belga/publish/belga_newsml_1_2.py, server/tests/publish/belga_newsml_1_2_text_tests.py
Add missing Label and Distribution values to NewsML
=> Add Label and Distribution [SDBELGA-475]

server/belga/macros/desk_incoming_rule_macro.py
=> only set default metadata for fetched/routed content

server/belga/publish/belga_newsml_1_2.py, server/tests/publish/belga_newsml_1_2_text_tests.py
=> change distribution value in belga newsml

server/belga/publish/belga_newsml_1_2.py, server/tests/publish/belga_newsml_1_2_text_tests.py
=> fix format name for belga gallery

server/belga/io/feed_parsers/base_belga_newsml_1_2.py, server/belga/io/feed_parsers/belga_newsml_1_2.py, server/tests/io/feed_parsers/belga_ats_newsml_1_2_test.py, server/tests/io/feed_parsers/belga_newsml_1_2_test.py
=> only parse authors with matching user in SD

server/belga/publish/belga_newsml_1_2.py, server/tests/publish/belga_newsml_1_2_text_tests.py
=> fix belga newsml gallery format

server/belga/publish/belga_newsml_1_2.py, server/tests/publish/belga_newsml_1_2_text_tests.py
=> fix belga newsml source output

client/superdesk.config.js
Hide the embargo field settings from the publish panel
=> Hide Embargo [SDBELGA-453]

client/superdesk.config.js
enable highlighting of search results
=> enable elasticHighlight

server/belga/signals/__init__.py, server/belga/signals/update.py, server/tests/signals/update_test.py
Karel confirmed, make it disable on any update.
=> Default 'coming up' time should be empty in update [SDBELGA-493]

client/belga/360archive/index.js, client/belga/360archive/views/search-panel.html, client/belga/belgapress/index.js, client/belga/belgapress/views/search-panel.html, client/belga/image/index.js, client/belga/image/views/search-panel.html, server/belga/search_providers.py, server/tests/search_providers/belga_360_archive_test.py, server/tests/search_providers/belga_image_test.py, server/tests/search_providers/belga_press_test.py
and do the type filtering via api
SDBELGA-482
=> fix client controller overriding each other

server/belga/publish/belga_newsml_1_2.py, server/tests/publish/belga_newsml_1_2_picture_tests.py, server/tests/publish/belga_newsml_1_2_text_tests.py, server/tests/publish/belga_newsml_1_2_video_tests.py
=> use belga mimetypes in belga newsml output

server/belga/publish/belga_newsml_1_2.py, server/tests/publish/belga_newsml_1_2_text_tests.py
=> change order of news components in belga newsml

server/belga/publish/belga_newsml_1_2.py, server/tests/publish/belga_newsml_1_2_text_tests.py
`body_html` was incorrectly parsed using XML parser.
fix SDBELGA-509
=> [PUBLISH][BELGA NEWSML] fix `body_html` parsing

client/superdesk.config.js
https://dev.sourcefabric.org/browse/SDBELGA-523
=> Add noPublishOnAuthoringDesk [SDBELGA-523]

client/extensions/iptc/src/extension.ts
https://dev.sourcefabric.org/browse/SDBELGA-526
=> Change default for services-products [SDBELGA-526]

server/belga/publish/belga_newsml_1_2.py, server/tests/fixtures/belga-newsml-1.2-SDBELGA-514.json, server/tests/publish/belga_newsml_1_2_items_chain_tests.py
When a picture is present several times in items chain, we output only
once.
SDBELGA-514
=> [PUBLISH][BELGA NEWSML]Output once pictures in items chain

client/extensions/belgaCoverage/package-lock.json, client/extensions/belgaCoverage/package.json, client/extensions/belgaCoverage/src/belga-coverage-carousel.tsx, client/extensions/belgaCoverage/src/belga-coverage-editor.tsx, client/extensions/belgaCoverage/src/belga-coverage-info.tsx, client/extensions/belgaCoverage/src/belga-coverage-preview.tsx, client/extensions/belgaCoverage/src/belga-image-api.ts, server/belga/publish/belga_newsml_1_2.py, server/tests/publish/belga_newsml_1_2_text_tests.py
=> implement multiple belga coverages in single item

client/extensions/belgaCoverage/src/belga-coverage-carousel.tsx, client/package-lock.json, client/package.json
Marking his one as `draft` until this PR https://github.com/superdesk/superdesk-client-core/pull/3912 is merged.
I will then update the commit sha for `client-core` in `package.json` and `package-lock.json` files
=> [SDBELGA-539] fix: Dont import css from ui-framework

client/belga/index.tsx, client/extensions/belgaCoverage/src/index.ts, client/extensions/iptc/src/extension.ts, client/extensions/saveArticleOnComingUpChange/src/extension.ts, client/extensions/updateArticleOnProfileChange/src/extension.ts, client/package-lock.json, client/package.json
This PR is only for testing. It will not be merged.
=> use client develop branch

server/settings.py
to allow searching for sign offs matching stop words
SDBELGA-417
=> fix elastic analyzer config

server/belga/io/feed_parsers/base_belga_newsml_1_2.py, server/belga/io/feed_parsers/belga_anp_newsml_1_2.py, server/belga/io/feed_parsers/belga_newsml_1_2.py, server/belga/io/feed_parsers/belga_tip_newsml_1_2.py, server/belga/publish/belga_newsml_1_2.py, server/data/vocabularies.json, server/settings.py, server/tests/io/feed_parsers/belga_anp_newsml_1_2_test.py, server/tests/io/feed_parsers/belga_ats_newsml_1_2_test.py, server/tests/io/feed_parsers/belga_newsml_1_2_test.py
store it as genre instead of subject, but for BC handle both
in the output
SDBELGA-568
=> fix genre handling

client/superdesk.config.js
Add config confirmDueDate for SDBELGA-574
=> FIX: The 'publish schedule' alert does not work for all publish options. [SDBELGA-574]

server/belga/io/feed_parsers/base_belga_newsml_1_2.py, server/data/vocabularies.json
=> fix genre vocabularies config

client/superdesk.config.js, server/data/config.json
=> move startingDay option from js file to database

client/index.tsx
=> fix registration of extensions

server/belga/io/feed_parsers/base_belga_newsml_1_2.py, server/belga/io/feed_parsers/belga_afp_newsml_1_2.py, server/belga/io/feed_parsers/belga_anp_newsml_1_2.py, server/belga/io/feed_parsers/belga_dpa_newsml_2_0.py, server/belga/io/feed_parsers/belga_newsml_mixin.py, server/tests/io/feed_parsers/belga_afp_newsml_1_2_test.py, server/tests/io/feed_parsers/belga_anp_newsml_1_2_test.py, server/tests/io/feed_parsers/belga_dpa_newsml_2_0_test.py, server/tests/io/feed_parsers/belga_efe_newsml_1_2_test.py, server/tests/io/feed_parsers/belga_kyodo_newsml_1_2_test.py, server/tests/io/feed_parsers/belga_tass_newsml_1_2_test.py, server/tests/io/fixtures/anp_belga.xml, server/tests/io/fixtures/dpa_newsml_2_0_belga.xml
similar to SDBELGA-521, we have to store data for ANP and DPA also.
=> Fix: Recognition of 'Country', 'Belga Keywords' and 'Country Keywords of AFP, ANP, DPA. [SDBELGA-521]

server/requirements.txt
Update requirement.txt to hotfix/2.3.4 [SDBELGA-581]
[SDBELGA-581]: https://sofab.atlassian.net/browse/SDBELGA-581
=> FIX:Gmail ingest failing on Belga Staging (Bel9) [SDBELGA-581]

client/package-lock.json, client/superdesk.config.js
=> enable due date prompt before publishing

server/belga/io/feed_parsers/belga_efe_newsml_1_2.py, server/belga/io/feed_parsers/belga_tass_newsml_1_2.py, server/tests/io/feed_parsers/belga_efe_newsml_1_2_test.py, server/tests/io/feed_parsers/belga_tass_newsml_1_2_test.py
store all the possible keywords for EFE and itartass
=> As an editor I like to see and search based on all keywords coming with the ingest sources EFE, Itartass [SDBELGA-566]

server/belga/io/feed_parsers/belga_newsml_1_2.py, server/belga/io/feed_parsers/belga_newsml_mixin.py, server/tests/io/feed_parsers/belga_newsml_1_2_test.py
Belga is not using the Abstract field, we already mapped the abstract data into the body_html field.
=> Import Belga biographies into Superdesk [SDBELGA-623]

server/belga/search_providers.py
To address the comment of client-side PR(https://github.com/superdesk/superdesk-client-core/pull/4080) we have created this one
=> Improve the Belga archive integration [SDBELGA-606]

server/belga/io/feed_parsers/belga_afp_newsml_1_2.py, server/tests/io/feed_parsers/belga_afp_newsml_1_2_test.py
=> Fix Subjects in belga AFP newsml 1.2 feedparser

server/belga/__init__.py, server/belga/search_providers.py
Here I have resolved issue mentioned on this comment :- https://sofab.atlassian.net/browse/SDBELGA-606?focusedCommentId=118630
=> Improve the Belga archive integration (Adding default params in Belga360ArchiveSearchProvider )  [SDBELGA-606]

server/belga/publish/belga_newsml_1_2.py, server/tests/publish/belga_newsml_1_2_text_tests.py
- for autorouted items it should use source name
- otherwise it should be always BELGA
SDBELGA-686 SDBELGA-685
=> Change creditline in Belga Newsml output
