server/data/planning_types.json

based on Belga feedback, the slugline in Event should not be required

changed event slugline: reguired = false

---

client/package.json

superdesk-client-core doesn't seem to be working with master of
superdesk-planning, so this patch restrict its version to 1.5

using superdesk-planning 1.5

---

.gitignore
server/belga/publish/belga_newsml_1_2.py
server/tests/publish/belga_newsml_1_2_tests.py

SDBELGA-154
- remove redundant `Duid`s
- improve `Authors`
- add `Source` to the output
- add images from a body to the output
- add related images to the output
- add image galleries to the output
- add graphics to the output
- add belga coverage to the output
- add related audio/video to the output
- add attached files to the output
⚠️ methods `_format_picture`, `_format_coverage`, `_format_audio`, `_format_video` and  `_format_attachment` are similar, but I've decided not to create 1 method for all cases, because there are still some differences.

Improve Belga NewsML output

---

README.md

Homebrew has removed mongo from its core formulas
`https://github.com/Homebrew/homebrew-core/pull/43770`

Update mongo install instruction on MacOS

---

server/belga/macros/__init__.py
server/belga/macros/set_default_metadata.py
server/belga/macros/set_default_metadata_with_translate.py
server/settings.py

A new `macros` directory is now available, and macros there are
automatically loaded on startup.
The `set_default_metadata` copied some metadata from desk's default
content template as requested in SDBELGA-142.
The `set_default_metadata_with_translate` do call `set_default_metadata`
then translate the item to the dest desk default content template
language and move it.
SDBELGA-142 and SDBELGA-143

[MACROS] added a `macros` directory + created set_default_metadata and set_default_metadata_with_translate

---

server/belga/io/feed_parsers/base_belga_newsml_1_2.py
server/belga/io/feed_parsers/belga_afp_newsml_1_2.py
server/belga/io/feed_parsers/belga_anp_newsml_1_2.py
server/belga/io/feed_parsers/belga_anpa.py
server/belga/io/feed_parsers/belga_ats_newsml_1_2.py
server/belga/io/feed_parsers/belga_dpa_newsml_2_0.py
server/belga/io/feed_parsers/belga_efe_newsml_1_2.py
server/belga/io/feed_parsers/belga_iptc7901.py
server/belga/io/feed_parsers/belga_tass_newsml_1_2.py
server/tests/io/feed_parsers/belga_afp_newsml_1_2_test.py
server/tests/io/feed_parsers/belga_anp_newsml_1_2_test.py
server/tests/io/feed_parsers/belga_anpa_test.py
server/tests/io/feed_parsers/belga_ats_newsml_1_2_test.py
server/tests/io/feed_parsers/belga_dpa_newsml_2_0_test.py
server/tests/io/feed_parsers/belga_efe_newsml_1_2_test.py
server/tests/io/feed_parsers/belga_iptc7901_test.py
server/tests/io/feed_parsers/belga_tass_newsml_1_2_test.py
server/tests/io/fixtures/afp_belga.xml
server/tests/io/fixtures/ats.txt
server/tests/io/fixtures/kyodo.txt

SDBELGA-221: The metadata of the DPA ingest is not mapped correctly. 
'News Services' has to be 'NEWS'
'News Products' has to be 'GENERAL', 'ECONOMY', 'SPORTS' or 'CULTURE' as stated in https://dev.sourcefabric.org/browse/SDBELGA-151
'Credits' has to be 'DPA'
'Distribution' has to be 'default'
'City' has to be prefilled based on the original
'Country' has to be prefilled based on the original
'Editorial info' has to be empty 
SDBELGA-222.
'Credits' has to be 'AFP'
'Distribution' has to be 'default'
'Label' has to be empty
SDBELGA-223.
'Credits' has to be 'ANP'
'Distribution' has to be 'default'
update other  TASS, EFE
'Credits' has to be 'TASS','EFE'
'Distribution' has to be 'default'
Update unit-test

Update metadata for inject

---

server/belga/io/feed_parsers/belga_anp_newsml_1_2.py
server/tests/io/feed_parsers/belga_anp_newsml_1_2_test.py

This PR set `slugline` to empty for all ANP ingest items.
For `storytags`, it seems the errors came from [setting storytags `id` to `keywords`](https://user-images.githubusercontent.com/45254285/70695087-87d90980-1cf3-11ea-8fbc-7202859aabf5.png) in vocabularies

[SDBELGA-251] Fix ANP ingest mapping for slugline and storytag

---

server/belga/search_providers.py
server/tests/belga_360_archive_test.py
server/tests/fixtures/belga-360archive-search.json

Changes:
- Map field `topic` from belga 360 to `slugline` in superdesk

[SDBELGA-242] Add slugline for belga 360 search item

---

server/belga/io/feed_parsers/base_belga_newsml_1_2.py
server/belga/io/feed_parsers/belga_ats_newsml_1_2.py
server/belga/io/feed_parsers/belga_dpa_newsml_2_0.py
server/belga/io/feed_parsers/belga_newsml_mixin.py
server/belga/io/feed_parsers/belga_tass_newsml_1_2.py
server/tests/io/feed_parsers/belga_afp_newsml_1_2_test.py
server/tests/io/feed_parsers/belga_dpa_newsml_2_0_test.py
server/tests/io/feed_parsers/belga_efe_newsml_1_2_test.py
server/tests/io/feed_parsers/belga_kyodo_newsml_1_2_test.py
server/tests/io/feed_parsers/belga_tass_newsml_1_2_test.py
server/tests/io/fixtures/kyodo_newsml_1_2_belga.xml
server/tests/io/fixtures/tass_belga.xml

Add multilingual country support for following NewsML format:
- AFP
- DPA (xml)
- EFE
- Kyoudo
Following format uses two character country code so it will always empty:
- [ANP](https://github.com/idsvn/superdesk-belga/blob/SDBELGA-266/server/tests/io/fixtures/anp_belga.xml#L58)
- [ATS](https://github.com/idsvn/superdesk-belga/blob/SDBELGA-266/server/tests/io/fixtures/ats_newsml_1_2_belga.xml#L64)
For ATS, DPA text, from what we saw, we currently don't parse country
For TASS, if we use [NewsComponent/NewsComponent](https://github.com/idsvn/superdesk-belga/blob/SDBELGA-266/server/belga/io/feed_parsers/belga_tass_newsml_1_2.py#L76), `vocabularies` service for `country` will return None, @ride90 Could you give us your opinion on this?
SDBELGA-266

[SDBELGA-266] Add multilingual country for belga ingest item

---

server/belga/io/feed_parsers/belga_afp_newsml_1_2.py
server/tests/io/feed_parsers/belga_afp_newsml_1_2_test.py
server/tests/io/fixtures/afp_belga.xml

This issue is related to https://github.com/superdesk/superdesk-belga/pull/65 (SDBELGA-181), where we will use first line of body as its headline.
If we ingest AFP file with the following body, it will fail
```xml
<body.content><p>example</p><p>abc</p></body.content>
```
Because we assume that the body will _always_ contains newline break, as such, we pass to XML parser two node **without parent**
In addition to fixing above issues, we also add some fixes:
- Handle `h2` tag (Superdesk client only support this header in body), though we saw that most of provided files had its body be wrapped in `p` tag
- Remove linebreak (`<p><br/></p>`) and empty tag (`<p>   </p>` or `<p></p>`)
SDBELGA-263

[SDBELGA-263] Fix ingest error on importing AFP without headline

---

server/belga/search_providers.py
server/tests/belga_image_test.py

seems like the server uses decoded url to check
signature so it must match
SDBELGA-298

fix belga image auth for complex queries

---

server/belga/io/feed_parsers/belga_newsml_1_2.py
server/tests/io/feed_parsers/belga_remote_newsml_1_2_test.py
server/tests/io/feed_parsers/belga_tip_newsml_1_2_test.py

When using ingest routing, Tips ingest (and Belga NewsML 1.2) does not display desks name, only **fetched in**
Most of TIPS files have version 0, so it is [excluded](https://github.com/superdesk/superdesk-core/blob/develop/apps/search/__init__.py#L77) from `search` service, the UI is using `search` service to fetch desk of ingested item, hence the bug.
SDBELGA-305

[SDBELGA-305] Fix Tips does not display desk after fetched

---

.travis.yml
server/belga/__init__.py
server/belga/macros/brief_internal_routing.py
server/tests/macros/brief_internal_routing_macro_test.py

- ignore items with non TEXT profile and with long body
- fix time selected when de-scheduling the item
- schedule new item 30m after publishing text in case it's scheduled
- handle validation error for newly create items to avoid client error
SDBELGA-315 SDBELGA-316 SDBELGA-318 SDBELGA-319

fix brief internal destination macro

---

server/belga/macros/unmark_from_user.py
server/belga/unmark_user_when_moved_to_incoming_stage.py
server/settings.py
server/tests/macros/unmark_from_user_test.py

there is both macro and a signal handler, so it will work
on inline stage out of the box and if needed it can be configured
via macro for other stages.
requires https://github.com/superdesk/superdesk-core/pull/1815
SDBELGA-314

implement unsetting of user when sent to incoming stage

---

server/belga/search_providers.py
server/tests/belga_360_archive_test.py

- Fix can't drag Belga 360 Archive item to **related article**, mainly because of [getSuperdeskType](https://github.com/superdesk/superdesk-client-core/blob/develop/scripts/core/utils.ts#L33) which is used in [RelatedItemsDirective](https://github.com/superdesk/superdesk-client-core/blob/develop/scripts/apps/relations/directives/RelatedItemsDirective.ts#L114)
- Change item's state to `published`
SDBELGA-351

[SDBELGA-351] Fix can't drag belga360 item to related article

---

server/belga/io/feed_parsers/belga_remote_newsml_1_2.py

```python
os.path.join('/home/ids', '/attachments/image.png') => /attachments/image.png
os.path.join('/home/ids', 'attachments/image.png') => /home/ids/attachments/image.png
```
Used in https://github.com/superdesk/superdesk-core/blob/develop/superdesk/io/feeding_services/file_service.py#L152
SDBELGA-365

[SDBELGA-365] Fix wrong remote attachments path

---

server/belga/publish/belga_newsml_1_2.py
server/tests/publish/belga_newsml_1_2_picture_tests.py
server/tests/publish/belga_newsml_1_2_text_tests.py
server/tests/publish/belga_newsml_1_2_video_tests.py

SDBELGA-367 Add video thumbnail (preview picture) to Belga NewsML output
SDBELGA-375 NewsItemType field in Belga NewsML export must have value "NEWS" instead of "News"

Add video thumbnail (preview picture) to Belga NewsML output

---

server/belga/search_providers.py
server/tests/belga_360_archive_test.py

This is the same as https://github.com/superdesk/superdesk-belga/pull/177
If we understand correctly, based on [this line](https://github.com/superdesk/superdesk-client-core/blob/develop/scripts/apps/relations/directives/RelatedItemsDirective.ts#L93), any item does not have type `superdesk.item.text`/picture/video, could not add as related item because [event is removed](https://github.com/superdesk/superdesk-client-core/blob/develop/scripts/apps/relations/directives/RelatedItemsDirective.ts#L102), but for some odd reason, Firefox still trigger event while Chrome does not, we have looked into it but still not sure what's problem with Firefox?!
@ride90 Is there anyway to custom [`ALLOWED_TYPE`](https://github.com/superdesk/superdesk-client-core/blob/develop/scripts/apps/relations/directives …

[SDBELGA-376] Fix unable add belga archive as related

---

client/belga/360archive/BelgaSearchPanelController.ts
client/belga/360archive/views/search-panel.html
server/belga/search_providers.py
server/tests/belga_360_archive_test.py
server/tests/fixtures/belga-360archive-search.json

1. Display date for Archive search item (SDBELGA-271)
Map `firstcreated` and `versioncreated` (used in [listItems](https://github.com/superdesk/superdesk-client-core/blob/develop/scripts/apps/search/components/ListItemInfo.tsx#L56) > [firstLine](https://github.com/superdesk/superdesk-client-core/blob/develop/scripts/apps/search/constants.ts#L52))
Should we also map `firstpublished` field for using in [Belga NewsML export](https://github.com/superdesk/superdesk-belga/blob/master/server/belga/publish/belga_newsml_1_2.py#L333)?
2. Add advanced search, search parameters are provided in **SDBELGA-173**:
- Search by headline is removed, based on @karelpetrak 's feedback, user should use full text search
- Search by **period** will override search by **date**
- For 24h period, because belga APIs …

[SBELGA-271][SDBELGA-288] Belga Archive Advanced Search

---

server/belga/search_providers.py
server/tests/search_providers/belga_360_archive_test.py

Display profile for Belga Archive items
- Use profile in `content_profiles.json` instead of `content_profiles` service as we have discussed
- If profile is `Short`, use `Text`, and leave it empty if it does not exist in superdesk
SDBELGA-410

[SDBELGA-410] Add profile for belga archive items

---

client/belga/image/BelgaSearchPanelController.ts
client/belga/image/views/search-panel.html
client/package.json
server/belga/search_providers.py
server/requirements.txt
server/tests/search_providers/belga_image_test.py

- Remove options search by `Last * hours`
- Add search by Date
- Upgrade `superdesk-analytics` to `v1.33.4`, this does not affect server, as we are using `develop` branch
*For Belga Image API, please check SDBELGA-9*
SDBELGA-253

[SDBELGA-253] Add search by date for Belga Image

---

server/belga/macros/brief_internal_routing.py
server/data_updates/00007_20201228-144144_content_types.py
server/tests/macros/brief_internal_routing_macro_test.py

SDBELGA-436
We store fixed content profiles in the json file and these profiles were imported during init data cmnd.
On Belga stage/prod instance content profiles were also created manually (which is wrong), so at the end, it was a conflict between imported (correct) profiles and manually created. 
This PR does next steps:
- replace **manually created** `data.profile` id with **the content profile from json** in `content_templates`
- replace **manually created** `default_content_profile` id with **the content profile from json** in `desks`
- replace **manually created** `profile` id with **the content profile from json** in `archive`
- replace **manually created** `profile` id with **the content profile from json** in `archive.associations.*.profile`
- replace **manually created** …

Sort out content profiles naming in staging and production

---

server/belga/io/feed_parsers/base_belga_newsml_1_2.py
server/belga/io/feed_parsers/belga_dpa_newsml_2_0.py
server/belga/io/feed_parsers/belga_newsml_mixin.py
server/tests/io/feed_parsers/belga_afp_newsml_1_2_test.py
server/tests/io/feed_parsers/belga_kyodo_newsml_1_2_test.py

related to [SDBELGA-566] and [SDBELGA-521]
[SDBELGA-566]: https://sofab.atlassian.net/browse/SDBELGA-566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SDBELGA-521]: https://sofab.atlassian.net/browse/SDBELGA-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIX: Resolve belga-keywords, country and country keywords issue in belga specific ANP, AFP, DPA, EFE, Itartass parsers

---

server/belga/search_providers.py

In some cases we got `data["comment] =  "" `, so here we handle it.

Belga archive API: Provide first published timestamp for items of type related [SDBELGA-631]
